apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doc-main-service
  namespace: default
spec:
  ingressClassName: kong
  rules:
    - host: doc.rabbitmq.hcmus.edu.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: doc-rabbitmq
                port:
                  number: 15672
    - host: doc.keycloak.hcmus.edu.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: doc-keycloak
                port:
                  number: 8180
    - host: doc.main.service.hcmus.edu.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: doc-main-service
                port:
                  number: 8080
