# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: DOC build and push to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK Temurin-17.0.5
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.5'

      - name: Test
        run: mvn clean test -DskipTypescriptGenerator=true

      - name: Build
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: hcmusdoc/doc-main-service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
